.TH "C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp/ADC.c" 3 "Wed Apr 28 2021" "Version 1.0" "Lab 12: Data Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp/ADC.c
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'DOG_LCD\&.h'\fP
.br
\fC#include 'ADC\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_CPU\fP   4000000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_adc\fP (void)"
.br
.ti -1c
.RI "void \fBconvert\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBhex\fP [16] = '0123456789ABCDEF'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define F_CPU   4000000"

.SH "Function Documentation"
.PP 
.SS "void convert (void)"

.SS "void init_adc (void)"

.SH "Variable Documentation"
.PP 
.SS "char hex[16] = '0123456789ABCDEF'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 12: Data Logger from the source code\&.
