.TH "C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp/ADC.h" 3 "Wed Apr 28 2021" "Version 1.0" "Lab 12: Data Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp/ADC.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRES12_Bm\fP   0x00"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBupdate_lcd_dog\fP (void)"
.br
.ti -1c
.RI "void \fBinit_adc\fP (void)"
.br
.ti -1c
.RI "void \fBconvert\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile uint16_t \fBresult\fP"
.br
.ti -1c
.RI "volatile uint8_t \fBtemp\fP"
.br
.ti -1c
.RI "volatile int \fBboolean\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RES12_Bm   0x00"

.SH "Function Documentation"
.PP 
.SS "void convert (void)"

.SS "void init_adc (void)"

.SS "void update_lcd_dog (void)"

.SH "Variable Documentation"
.PP 
.SS "volatile int boolean"

.SS "volatile uint16_t result"

.SS "volatile uint8_t temp"

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 12: Data Logger from the source code\&.
