.TH "C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp Directory Reference" 3 "Wed Apr 28 2021" "Version 1.0" "Lab 12: Data Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBADC\&.c\fP"
.br
.ti -1c
.RI "file \fBADC\&.h\fP"
.br
.ti -1c
.RI "file \fBDOG_LCD\&.c\fP"
.br
.ti -1c
.RI "file \fBDOG_LCD\&.h\fP"
.br
.ti -1c
.RI "file \fBDS1306_RTCDrivers\&.c\fP"
.br
.ti -1c
.RI "file \fBDS1306_RTCDrivers\&.h\fP"
.br
.ti -1c
.RI "file \fBFSM\&.c\fP"
.br
.ti -1c
.RI "file \fBFSM\&.h\fP"
.br
.ti -1c
.RI "file \fBFSM_Methods\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBUSART3\&.c\fP"
.br
.ti -1c
.RI "file \fBUSART3\&.h\fP"
.br
.in -1c
