.TH "C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp/DOG_LCD.h" 3 "Wed Apr 28 2021" "Version 1.0" "Lab 12: Data Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp/DOG_LCD.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlcd_spi_transmit_CMD\fP (unsigned char cmd)"
.br
.ti -1c
.RI "void \fBlcd_spi_transmit_DATA\fP (unsigned char cmd)"
.br
.ti -1c
.RI "void \fBinit_spi_lcd\fP (void)"
.br
.ti -1c
.RI "void \fBinit_lcd_dog\fP (void)"
.br
.ti -1c
.RI "void \fBupdate_lcd_dog\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBdsp_buff1\fP [17]"
.br
.ti -1c
.RI "char \fBdsp_buff2\fP [17]"
.br
.ti -1c
.RI "char \fBdsp_buff3\fP [17]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init_lcd_dog (void)"

.SS "void init_spi_lcd (void)"

.SS "void lcd_spi_transmit_CMD (unsigned char cmd)"

.SS "void lcd_spi_transmit_DATA (unsigned char cmd)"

.SS "void update_lcd_dog (void)"

.SH "Variable Documentation"
.PP 
.SS "char dsp_buff1[17]"

.SS "char dsp_buff2[17]"

.SS "char dsp_buff3[17]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 12: Data Logger from the source code\&.
