.TH "C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp/DS1306_RTCDrivers.c" 3 "Wed Apr 28 2021" "Version 1.0" "Lab 12: Data Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vleen/Documents/Atmel Studio/7.0/display_time_temp/display_time_temp/DS1306_RTCDrivers.c
.SH SYNOPSIS
.br
.PP
\fC#include <util/delay\&.h>\fP
.br
\fC#include <avr/io\&.h>\fP
.br
\fC#include 'DS1306_RTCDrivers\&.h'\fP
.br
\fC#include 'DOG_LCD\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_CPU\fP   4000000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSPI_rtc_ds1306_config\fP (void)"
.br
.ti -1c
.RI "void \fBblock_write_RTC\fP (volatile unsigned char *array_ptr, unsigned char strt_addr, unsigned char count)"
.br
.ti -1c
.RI "void \fBblock_read_RTC\fP (volatile unsigned char *array_ptr, unsigned char strt_addr, unsigned char count)"
.br
.ti -1c
.RI "void \fBwrite_RTC\fP (unsigned char reg_RTC, unsigned char data_RTC)"
.br
.ti -1c
.RI "unsigned char \fBread_RTC\fP (unsigned char reg_RTC)"
.br
.ti -1c
.RI "void \fBwrite_read_RTC_test\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile unsigned char \fBRTC_time_date_write\fP [7]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define F_CPU   4000000"

.SH "Function Documentation"
.PP 
.SS "void block_read_RTC (volatile unsigned char * array_ptr, unsigned char strt_addr, unsigned char count)"

.SS "void block_write_RTC (volatile unsigned char * array_ptr, unsigned char strt_addr, unsigned char count)"

.SS "unsigned char read_RTC (unsigned char reg_RTC)"

.SS "void SPI_rtc_ds1306_config (void)"

.SS "void write_read_RTC_test (void)"

.SS "void write_RTC (unsigned char reg_RTC, unsigned char data_RTC)"

.SH "Variable Documentation"
.PP 
.SS "volatile unsigned char RTC_time_date_write[7]"
\fBInitial value:\fP
.PP
.nf
= { 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 12: Data Logger from the source code\&.
