.TH "transition" 3 "Wed Apr 28 2021" "Version 1.0" "Lab 12: Data Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transition
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FSM\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBkey\fP \fBkeyval\fP"
.br
.ti -1c
.RI "\fBstate\fP \fBnext_state\fP"
.br
.ti -1c
.RI "\fBtask_fn_ptr\fP \fBtf_ptr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBkey\fP keyval"

.SS "\fBstate\fP next_state"

.SS "\fBtask_fn_ptr\fP tf_ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 12: Data Logger from the source code\&.
