.TH "C:/Users/vleen/Documents/Atmel Studio/7.0/lab10/testproject Directory Reference" 3 "Wed Apr 14 2021" "Version 1.0" "Temperature Measurement Multi Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vleen/Documents/Atmel Studio/7.0/lab10/testproject Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBADC\&.c\fP"
.br
.ti -1c
.RI "file \fBADC\&.h\fP"
.br
.ti -1c
.RI "file \fBDOG_LCD\&.c\fP"
.br
.ti -1c
.RI "file \fBDOG_LCD\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.in -1c
