.TH "C:/Users/vleen/Documents/Atmel Studio/7.0/lab10/testproject/DOG_LCD.h" 3 "Wed Apr 14 2021" "Version 1.0" "Temperature Measurement Multi Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vleen/Documents/Atmel Studio/7.0/lab10/testproject/DOG_LCD.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlcd_spi_transmit_CMD\fP (unsigned char cmd)"
.br
.ti -1c
.RI "void \fBlcd_spi_transmit_DATA\fP (unsigned char cmd)"
.br
.ti -1c
.RI "void \fBinit_spi_lcd\fP (void)"
.br
.ti -1c
.RI "void \fBinit_lcd_dog\fP (void)"
.br
.ti -1c
.RI "void \fBupdate_lcd_dog\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBdsp_buff1\fP [17]"
.br
.ti -1c
.RI "char \fBdsp_buff2\fP [17]"
.br
.ti -1c
.RI "char \fBdsp_buff3\fP [17]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init_lcd_dog (void)"

.PP
Definition at line 153 of file DOG_LCD\&.c\&.
.SS "void init_spi_lcd (void)"

.PP
Definition at line 52 of file DOG_LCD\&.c\&.
.SS "void lcd_spi_transmit_CMD (unsigned char cmd)"

.PP
Definition at line 88 of file DOG_LCD\&.c\&.
.SS "void lcd_spi_transmit_DATA (unsigned char cmd)"

.PP
Definition at line 121 of file DOG_LCD\&.c\&.
.SS "void update_lcd_dog (void)"

.PP
Definition at line 221 of file DOG_LCD\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "char dsp_buff1[17]"

.PP
Definition at line 19 of file DOG_LCD\&.h\&.
.SS "char dsp_buff2[17]"

.PP
Definition at line 20 of file DOG_LCD\&.h\&.
.SS "char dsp_buff3[17]"

.PP
Definition at line 21 of file DOG_LCD\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Temperature Measurement Multi Module from the source code\&.
