.TH "C:/Users/vleen/Documents/Atmel Studio/7.0/lab10/testproject/main.c" 3 "Wed Apr 14 2021" "Version 1.0" "Temperature Measurement Multi Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/vleen/Documents/Atmel Studio/7.0/lab10/testproject/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <util/delay\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'DOG_LCD\&.h'\fP
.br
\fC#include 'ADC\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_CPU\fP   4000000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define F_CPU   4000000"

.PP
Definition at line 23 of file main\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 35 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Temperature Measurement Multi Module from the source code\&.
