DOG_LCD.h
char dsp_buff1[17][17]
Referenced by update_lcd_dog, write_read_RTC_test.
char dsp_buff2[17][17]
Referenced by convert, update_lcd_dog.
char dsp_buff3[17][17]
Referenced by update_lcd_dog.
void lcd_spi_transmit_CMD(unsigned char cmd)
Referenced by init_lcd_dog, update_lcd_dog.
void lcd_spi_transmit_DATA(unsigned char cmd)
Referenced by update_lcd_dog.
void init_spi_lcd(void)
Referenced by init_lcd_dog, update_lcd_dog.
void init_lcd_dog(void)
References init_spi_lcd, lcd_spi_transmit_CMD.
void update_lcd_dog(void)