DOG_LCD.c
F_CPU
void init_spi_lcd(void)
Referenced by init_lcd_dog, update_lcd_dog.
void lcd_spi_transmit_CMD(unsigned char cmd)
Referenced by init_lcd_dog, update_lcd_dog.
void lcd_spi_transmit_DATA(unsigned char data)
Referenced by update_lcd_dog.
void init_lcd_dog(void)
References init_spi_lcd, lcd_spi_transmit_CMD.
void update_lcd_dog(void)
References dsp_buff1, dsp_buff2, dsp_buff3, init_spi_lcd, lcd_spi_transmit_CMD, lcd_spi_transmit_DATA.
Referenced by ISR.