DS1306_RTCDrivers.c
F_CPU
volatile unsigned char RTC_time_date_write[7][7]
Referenced by write_read_RTC_test.
void SPI_rtc_ds1306_config(void)
Referenced by main.
void block_write_RTC(volatile unsigned char *array_ptr, unsigned char strt_addr, unsigned char count)
Referenced by write_read_RTC_test.
void block_read_RTC(volatile unsigned char *array_ptr, unsigned char strt_addr, unsigned char count)
Referenced by write_read_RTC_test.
void write_RTC(unsigned char reg_RTC, unsigned char data_RTC)
Referenced by enter_hour_fn, enter_min_fn, enter_sec_fn, initInterupt, write_read_RTC_test.
unsigned char read_RTC(unsigned char reg_RTC)
References temp.
Referenced by set_hours_fn, set_mins_fn, set_sec_fn.
void write_read_RTC_test()
References block_read_RTC, block_write_RTC, CTRL_REG, dsp_buff1, RTC_time_date_read, RTC_time_date_write, RTCRead, RTCWrite, write_RTC.
Referenced by ISR.