USART3.c
F_CPU
void init_USART()
References BAU.
Referenced by main.
void transmit_USART(int data)
References temp.
Referenced by set_hours_fn, set_mins_fn, set_sec_fn.