ADC.c
F_CPU
char hex[16][16]
Referenced by displayVolt.
void init_adc(void)
References RES12_Bm.
Referenced by main.
void convert()
References convertToBCD, displayVolt, result.
Referenced by main.
void displayVolt(uint16_t r)
References dsp_buff1, hex, tempHex.
Referenced by convert.
uint32_t convertToBCD(uint16_t val)
References result.
Referenced by convert.