ADC.h
RES12_Bm
char tempHex[3][3]
Referenced by displayVolt.
volatile uint16_t result
Referenced by convert, convertToBCD.
volatile uint8_t temp
volatile int boolean
void update_lcd_dog(void)
References dsp_buff1, dsp_buff2, dsp_buff3, init_spi_lcd, lcd_spi_transmit_CMD, lcd_spi_transmit_DATA.
Referenced by main.
void convert(void)
References convertToBCD, displayVolt, result.
Referenced by main.
void displayVolt(uint16_t r)
References dsp_buff1, hex, tempHex.
Referenced by convert.
uint32_t convertToBCD(uint16_t dec)
References result.
Referenced by convert.